# the developer compose file
services:
  web: #the website
    build: . #Build current directory
    entrypoint: [ "sh", "-c", "flask --app 'twidilers:create_app()' db upgrade && exec gunicorn --bind 0.0.0.0:8000 'twidilers:create_app()' --workers 4 --graceful-timeout 30" ]
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on: #A healthy database
      db:
        condition: service_healthy 
    links: # not required but links it to the db
      - db
    ports: # map to port 80 for ease of connecting
      - 80:5000
    volumes:
      - ./:/app # links the current directory so the flask auto-reloader works at run-time
  db: #The database
    image: postgres #pull from most recent postgres
    volumes:
      - ./pData:/var/lib/postgresql/data #Link the postgres data to the pData directory for data persistence accross containers
    environment: #some postgres-specific env vars
      - POSTGRES_USER=${POSTGRES_USER:?Set POSTGRES_USER in the environment}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in the environment}
      - POSTGRES_DB=${POSTGRES_DB:?Set POSTGRES_DB in the environment}
    healthcheck: #tells the website whether the database is ready to startup
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s #How often to check
      timeout: 10s #How long it has to respond
      retries: 10 #How many retries it has
      start_period: 1s #The delay after starting to check