[project]
name = "twidilers"
dependencies = [
    "flask",
    "Flask-SQLAlchemy",
    "python-dotenv",
    "psycopg2",
    "bcrypt",
]
version='1.0'
description='A wonderful website'

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"