"""Initial migration

Revision ID: 270025091fe0
Revises: 
Create Date: 2025-01-17 19:51:03.673114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '270025091fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('displayname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(), nullable=True),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('setup', sa.Boolean(), nullable=False),
    sa.Column('is_oauth', sa.Boolean(), nullable=False),
    sa.Column('userdata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('musics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('displayname', sa.String(), nullable=False),
    sa.Column('instruments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follow',
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('following_id', 'follower_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('follow')
    op.drop_table('musics')
    op.drop_table('accounts')
    # ### end Alembic commands ###
