"""Migration Message Here3

Revision ID: e9133ab1fb8f
Revises: 2e046ba4f57e
Create Date: 2025-07-09 20:08:38.348634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9133ab1fb8f'
down_revision = '2e046ba4f57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
